### ISSUE TITLE
「新規アプリケーションを作成」でアプリ名は前後の空白を削除してほしい

### ISSUE THREAD

**Issue by scivola** [pepabo/sqale-support#13]
新規アプリケーションを作成するとき，打ち間違いを防ぐため，アプリケーション名を元資料からコピペで入力することがあります。

ところが，コピペのときに文字列の前か後ろにスペースがくっついていることが意外にあります。

すると「名前は不正な値です。」と出るのですが，見た目ではなかなか分らないので悩むことになります。

ついでに，全角英数字の半角化くらいやってくれても。

**Comment by kurotaky** [comment]
@scivola 
アプリケーション名の前後にwhitespaceが含まれる場合は、
それを削除するように対応しました。:octocat:

**Comment by scivola** [comment]
ありがとうございました。
