### ISSUE TITLE
アカウントあたりのアプリ数制限をゆるく

### ISSUE THREAD

**Issue by scivola** [pepabo/sqale-support#14]
1 アカウントで 5 アプリケーションしか作れないのは不便すぎます。

**Comment by kurotaky** [comment]
@scivola 
コメントありがとうございます。
現在は1アカウントでアプリケーションは10個(お試しアプリケーションは5個まで)
作成できるように対応いたしました。

**Comment by scivola** [comment]
本当は何十個も作れるようにしてほしいのですが，これで当面の危機は免れそうです。
ありがとうございました。
